// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReFitPatientData;

namespace ReFitPatientCore.Migrations
{
    [DbContext(typeof(PatientContext))]
    [Migration("20210430100601_InitialDBCreation")]
    partial class InitialDBCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReFitPatientCore.Domain.Exercise", b =>
                {
                    b.Property<int>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExercisePackageID")
                        .HasColumnType("int");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.HasKey("ExerciseID");

                    b.HasIndex("ExercisePackageID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.ExercisePackage", b =>
                {
                    b.Property<int>("ExercisePackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PackageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSSN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ExercisePackageID");

                    b.HasIndex("PatientSSN");

                    b.ToTable("ExercisePackages");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.Journal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BendAngle")
                        .HasColumnType("float");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JournalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PainScale")
                        .HasColumnType("float");

                    b.Property<string>("PatientSSN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("PatientSSN");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.Patient", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.Exercise", b =>
                {
                    b.HasOne("ReFitPatientCore.Domain.ExercisePackage", null)
                        .WithMany("ExerciseList")
                        .HasForeignKey("ExercisePackageID");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.ExercisePackage", b =>
                {
                    b.HasOne("ReFitPatientCore.Domain.Patient", null)
                        .WithMany("PackageList")
                        .HasForeignKey("PatientSSN");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.Journal", b =>
                {
                    b.HasOne("ReFitPatientCore.Domain.Patient", null)
                        .WithMany("JournalList")
                        .HasForeignKey("PatientSSN");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.ExercisePackage", b =>
                {
                    b.Navigation("ExerciseList");
                });

            modelBuilder.Entity("ReFitPatientCore.Domain.Patient", b =>
                {
                    b.Navigation("JournalList");

                    b.Navigation("PackageList");
                });
#pragma warning restore 612, 618
        }
    }
}
